import type { FindingSeverity, ReleaseVerdict, ReqAnalysis } from './types.js';

const SEVERITY_ORDER: readonly FindingSeverity[] = ['critical', 'high', 'medium', 'low', 'info'];

function cell(text: string): string {
  return text.replaceAll('|', '\\|').replaceAll(/\r?\n/g, ' ');
}

/** Markdown for the work-item discussion. Advisory: it informs the team, the gates decide. */
export function renderReqAnalysisComment(analysis: ReqAnalysis): string {
  const findings = [...analysis.findings].sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity),
  );
  const lines = [
    `**AI QA analysis (advisory)** — risk: **${analysis.riskTier}**, readiness: **${analysis.readiness}**`,
    '',
    analysis.summary,
    '',
  ];

  if (findings.length > 0) {
    lines.push('| Severity | Dimension | Finding | Suggestion |', '|---|---|---|---|');
    for (const f of findings) {
      lines.push(`| ${f.severity} | ${cell(f.dimension)} | ${cell(f.title)} | ${cell(f.suggestion)} |`);
    }
    lines.push('');
  }
  if (analysis.openQuestions.length > 0) {
    lines.push('**Open questions**', ...analysis.openQuestions.map((q) => `- ${q}`), '');
  }
  if (analysis.proposedAcceptanceCriteria.length > 0) {
    lines.push('**Proposed acceptance criteria**', '', '```gherkin', ...analysis.proposedAcceptanceCriteria, '```', '');
  }
  lines.push('_Generated by the qa-platform `req-analyst` agent. Reply in this thread to challenge a finding._');
  return lines.join('\n');
}

/** Markdown for the pipeline summary tab. The deterministic gate result sits next to it and wins. */
export function renderReleaseVerdict(verdict: ReleaseVerdict): string {
  const label = { go: 'GO', 'go-with-risks': 'GO WITH RISKS', 'no-go': 'NO-GO' }[verdict.recommendation];
  const lines = [
    `## AI release recommendation (advisory): ${label}`,
    '',
    `Release \`${verdict.releaseId}\` · confidence ${Math.round(verdict.confidence * 100)}%`,
    '',
    verdict.summary,
    '',
  ];
  if (verdict.blockingIssues.length > 0) lines.push('### Blocking issues', ...verdict.blockingIssues.map((b) => `- ${b}`), '');
  if (verdict.risks.length > 0) {
    lines.push('### Risks', '| Severity | Risk | Mitigation |', '|---|---|---|');
    for (const r of verdict.risks) lines.push(`| ${r.severity} | ${cell(r.description)} | ${cell(r.mitigation)} |`);
    lines.push('');
  }
  lines.push('### Evidence', ...verdict.evidenceReviewed.map((e) => `- ${e.status.toUpperCase()}: ${e.source}${e.note ? ` — ${e.note}` : ''}`), '');
  lines.push('### Quality dimensions', ...verdict.dimensionCoverage.map((d) => `- ${d.dimension}: ${d.status}${d.note ? ` — ${d.note}` : ''}`), '');
  lines.push('_Generated by the qa-platform `release-judge` agent. Humans approve production._');
  return lines.join('\n');
}
